name: Python CI/CD #specifying the type or defines the name of the workflow

on: [push] #puts it in the file i created before or triggers the workflow/runs

jobs: #build the python file
  build: #this will execute everything under it
    runs-on: ubuntu-latest #specifies operating system could be macOS/windows
    steps:
      - name: Checkout code #read "clone" the repo so that it can be worked on during the job
        uses: actions/checkout@v3 #built in actions/creating the script of the action [checkout is built in]
      - name: Set up Python #install python package and set it up to use it in this package
        uses: actions/setup-python@v3 #built in action
        with: #the version of python
          python-version: '3.x' #any version above 3
      - name: Run Python script #run the script 
        run: python hello.py #give it any name i need
        #it will give an error if the file is not already in my repo
        #should run a file from my repo
